### ISSUE TITLE
🛑 Admin is down

### ISSUE THREAD

**Issue by ajs256** [obl-ong/status#6]
In [`7bda7aa`](https://github.com/obl-ong/status/commit/7bda7aafe20f90952d80594c422629780d1faa56
), Admin (https://admin.obl.ong/up) was **down**:
- HTTP code: 0
- Response time: 0 ms

**Comment by reesericci** [comment]
The proxmox was being wonky and I think I accidentally crashed the VM while working on the forum. I was also in class which explains the long delay to resolving the issue.
